export const INTERNET_RESOURCE_TYPES = [
  "app",
  "article",
  "blog",
  "book",
  "booklet",
  "brochure",
  "course",
  "crisisResource",
  "forum",
  "memorial",
  "peerSupportResource",
  "podcast",
  "podcastEpisode",
  "story",
  "therapyResource",
  "video",
  "webinar",
] as const;
