export const INTERNET_RESOURCE_TYPES = [
  "app",
  "article",
  "blog",
  "book",
  "community",
  "course",
  "forum",
  "memorial",
  "peerSupport",
  "podcast",
  "podcastEpisode",
  "printedMaterial",
  "story",
  "supportGroup",
  "therapyResource",
  "video",
  "webinar",
] as const;
