name = "grief-matters-cms"
main = "./worker/index.ts"
compatibility_date = "2024-09-08"
preview_urls = false

[assets]
directory = "./dist/"
not_found_handling = "single-page-application"
binding = "ASSETS"

[vars]
SANITY_STUDIO_PROJECT_ID = "vg3sb730"
SANITY_STUDIO_DATASET = "production"
SANITY_STUDIO_API_VERSION = '2023-07-16'

[[kv_namespaces]]
binding = "WGM_BROKEN_LINKS"
id = "c550797730cd46548c029305d481209c"
preview_id = "a7d4febae7d2471d90754d4b90913ecf"

[triggers]
crons = ["0 17 * * thu"]